/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/fnivek/Code/NASABotics/NASAboticsCode/AggreGator_ws/src/ladar/msg/processed_data.msg
 *
 */


#ifndef LADAR_MESSAGE_PROCESSED_DATA_H
#define LADAR_MESSAGE_PROCESSED_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ladar
{
template <class ContainerAllocator>
struct processed_data_
{
  typedef processed_data_<ContainerAllocator> Type;

  processed_data_()
    : connection(false)
    , coordinates()
    , slopes()
    , wall1()
    , wall2()
    , wall3()  {
    }
  processed_data_(const ContainerAllocator& _alloc)
    : connection(false)
    , coordinates(_alloc)
    , slopes(_alloc)
    , wall1(_alloc)
    , wall2(_alloc)
    , wall3(_alloc)  {
    }



   typedef uint8_t _connection_type;
  _connection_type connection;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _coordinates_type;
  _coordinates_type coordinates;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _slopes_type;
  _slopes_type slopes;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _wall1_type;
  _wall1_type wall1;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _wall2_type;
  _wall2_type wall2;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _wall3_type;
  _wall3_type wall3;




  typedef boost::shared_ptr< ::ladar::processed_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ladar::processed_data_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct processed_data_

typedef ::ladar::processed_data_<std::allocator<void> > processed_data;

typedef boost::shared_ptr< ::ladar::processed_data > processed_dataPtr;
typedef boost::shared_ptr< ::ladar::processed_data const> processed_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ladar::processed_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ladar::processed_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ladar

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'ladar': ['/home/fnivek/Code/NASABotics/NASAboticsCode/AggreGator_ws/src/ladar/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ladar::processed_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ladar::processed_data_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ladar::processed_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ladar::processed_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ladar::processed_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ladar::processed_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ladar::processed_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45feb168aa959d2161bb2a61b28d84be";
  }

  static const char* value(const ::ladar::processed_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45feb168aa959d21ULL;
  static const uint64_t static_value2 = 0x61bb2a61b28d84beULL;
};

template<class ContainerAllocator>
struct DataType< ::ladar::processed_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ladar/processed_data";
  }

  static const char* value(const ::ladar::processed_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ladar::processed_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool connection\n\
float32[] coordinates\n\
float32[] slopes\n\
float32[] wall1\n\
float32[] wall2\n\
float32[] wall3 \n\
";
  }

  static const char* value(const ::ladar::processed_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ladar::processed_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.connection);
      stream.next(m.coordinates);
      stream.next(m.slopes);
      stream.next(m.wall1);
      stream.next(m.wall2);
      stream.next(m.wall3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct processed_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ladar::processed_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ladar::processed_data_<ContainerAllocator>& v)
  {
    s << indent << "connection: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.connection);
    s << indent << "coordinates[]" << std::endl;
    for (size_t i = 0; i < v.coordinates.size(); ++i)
    {
      s << indent << "  coordinates[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.coordinates[i]);
    }
    s << indent << "slopes[]" << std::endl;
    for (size_t i = 0; i < v.slopes.size(); ++i)
    {
      s << indent << "  slopes[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.slopes[i]);
    }
    s << indent << "wall1[]" << std::endl;
    for (size_t i = 0; i < v.wall1.size(); ++i)
    {
      s << indent << "  wall1[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.wall1[i]);
    }
    s << indent << "wall2[]" << std::endl;
    for (size_t i = 0; i < v.wall2.size(); ++i)
    {
      s << indent << "  wall2[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.wall2[i]);
    }
    s << indent << "wall3[]" << std::endl;
    for (size_t i = 0; i < v.wall3.size(); ++i)
    {
      s << indent << "  wall3[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.wall3[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // LADAR_MESSAGE_PROCESSED_DATA_H
