/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/fnivek/git_hub/NASAboticsCode/AggreGator_ws/src/motor_controller/msg/AdaCmd.msg
 *
 */


#ifndef MOTOR_CONTROLLER_MESSAGE_ADACMD_H
#define MOTOR_CONTROLLER_MESSAGE_ADACMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_controller
{
template <class ContainerAllocator>
struct AdaCmd_
{
  typedef AdaCmd_<ContainerAllocator> Type;

  AdaCmd_()
    : device(0)
    , value()  {
    }
  AdaCmd_(const ContainerAllocator& _alloc)
    : device(0)
    , value(_alloc)  {
    }



   typedef uint8_t _device_type;
  _device_type device;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _value_type;
  _value_type value;


    enum { wheelMotors = 1 };
     enum { bucketDrum = 2 };
     enum { linearActuator = 3 };
 

  typedef boost::shared_ptr< ::motor_controller::AdaCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_controller::AdaCmd_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct AdaCmd_

typedef ::motor_controller::AdaCmd_<std::allocator<void> > AdaCmd;

typedef boost::shared_ptr< ::motor_controller::AdaCmd > AdaCmdPtr;
typedef boost::shared_ptr< ::motor_controller::AdaCmd const> AdaCmdConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_controller::AdaCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_controller::AdaCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg'], 'motor_controller': ['/home/fnivek/git_hub/NASAboticsCode/AggreGator_ws/src/motor_controller/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_controller::AdaCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_controller::AdaCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_controller::AdaCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_controller::AdaCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_controller::AdaCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_controller::AdaCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_controller::AdaCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17b118e43a2ec77ae6f6a1a688b9aeef";
  }

  static const char* value(const ::motor_controller::AdaCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17b118e43a2ec77aULL;
  static const uint64_t static_value2 = 0xe6f6a1a688b9aeefULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_controller::AdaCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_controller/AdaCmd";
  }

  static const char* value(const ::motor_controller::AdaCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_controller::AdaCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 device\n\
float32[] value\n\
\n\
uint8 wheelMotors=1\n\
uint8 bucketDrum=2\n\
uint8 linearActuator=3\n\
";
  }

  static const char* value(const ::motor_controller::AdaCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_controller::AdaCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.device);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AdaCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_controller::AdaCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_controller::AdaCmd_<ContainerAllocator>& v)
  {
    s << indent << "device: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.device);
    s << indent << "value[]" << std::endl;
    for (size_t i = 0; i < v.value.size(); ++i)
    {
      s << indent << "  value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.value[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROLLER_MESSAGE_ADACMD_H
