"""autogenerated by genpy from motorController/motorMSG.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class motorMSG(genpy.Message):
  _md5sum = "f0f17242b728bc2f9b92df609716f415"
  _type = "motorController/motorMSG"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
int16 LF_motorVal
int16 RF_motorVal
int16 RR_motorVal
int16 LR_motorVal

"""
  __slots__ = ['LF_motorVal','RF_motorVal','RR_motorVal','LR_motorVal']
  _slot_types = ['int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       LF_motorVal,RF_motorVal,RR_motorVal,LR_motorVal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(motorMSG, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.LF_motorVal is None:
        self.LF_motorVal = 0
      if self.RF_motorVal is None:
        self.RF_motorVal = 0
      if self.RR_motorVal is None:
        self.RR_motorVal = 0
      if self.LR_motorVal is None:
        self.LR_motorVal = 0
    else:
      self.LF_motorVal = 0
      self.RF_motorVal = 0
      self.RR_motorVal = 0
      self.LR_motorVal = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4h.pack(_x.LF_motorVal, _x.RF_motorVal, _x.RR_motorVal, _x.LR_motorVal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.LF_motorVal, _x.RF_motorVal, _x.RR_motorVal, _x.LR_motorVal,) = _struct_4h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4h.pack(_x.LF_motorVal, _x.RF_motorVal, _x.RR_motorVal, _x.LR_motorVal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.LF_motorVal, _x.RF_motorVal, _x.RR_motorVal, _x.LR_motorVal,) = _struct_4h.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4h = struct.Struct("<4h")
